### ISSUE TITLE
Critical injection failure on 1.20.2

### ISSUE THREAD

**Issue by lookeypl** [27rogi/Homabric#13]
Hi there!

When trying to run Homabric on Minecraft 1.20.2 with Fabric Loader 0.14.22 I couldn't start the server - it crashes with critical injection failures. I was removing mods one by one and found out the crash stopped happening when Homabric was disabled.

I later tested this locally with brand new 1.20.2 installation (only MC 1.20.2, Fabric 0.14.22 and Homabric 2.1.0) and I get similar "Critical injection failure". Downgrading Minecraft to 1.20.1 causes everything to load and work fine. Changing Fabric version did not affect this problem, so it has to be some 1.20.2 change that breaks Homabric.

Logs from client run:
```
[12:46:29] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.14.22
[12:46:29] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[12:46:29] [main/INFO]: Loading 24 mods:
	- fabricloader 0.14.22
	- homabric 2.1.0+1.20.x
	   |-- completeconfig-base 2.3.1
	   |-- fabric-api-base 0.4.29+b04edc7a77
	   |-- fabric-command-api-v2 2.2.11+b3afc78b77
	   |-- fabric-language-kotlin 1.9.5+kotlin.1.8.22
	   |    |-- org_jetbrains_kotlin_kotlin-reflect 1.8.22
	   |    |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.22
	   |    |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.22
	   |    |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.22
	   |    |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |    |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.1
	   |    |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.1
	   |    |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |    |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |    |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   |    \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d77
	   |-- server_translations_api 2.0.0+1.20
	   |    \-- packet_tweaker 0.4.0+1.19.4
	   \-- sgui 1.2.2+1.20
	- java 17
	- minecraft 1.20.2
[12:46:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Lukasz/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[12:46:29] [main/INFO]: Compatibility level set to JAVA_16
[12:46:29] [main/INFO]: Compatibility level set to JAVA_17
[12:46:32] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 92 milliseconds
[12:46:32] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2540 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2540 failed
	at net.minecraft.class_2943.<clinit>(class_2943.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.<clinit>(class_1297.java:226) ~[client-intermediary.jar:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:275) ~[client-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:797) ~[client-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1297) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1190) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 5 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2540 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2943.<clinit>(class_2943.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.<clinit>(class_1297.java:226) ~[client-intermediary.jar:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:275) ~[client-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:797) ~[client-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1297) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1190) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2943.<clinit>(class_2943.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.<clinit>(class_1297.java:226) ~[client-intermediary.jar:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:275) ~[client-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:797) ~[client-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1297) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1190) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method stapi$cacheStack(Lnet/minecraft/class_1799;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in server_translations_api.mixin.json:packet.PacketByteBufMixin from mod server_translations_api failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap server-translations-api-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2943.<clinit>(class_2943.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.<clinit>(class_1297.java:226) ~[client-intermediary.jar:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:275) ~[client-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:797) ~[client-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1297) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1190) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 5 more
Process exited with code 1.
```

**Comment by 27rogi** [comment]
Homabric is not yet updated for 1.20.2, sorry. Will try to update it as I get free time
